### ISSUE TITLE
Doesn't work with new Bootstrap 4 Beta

### ISSUE THREAD

**Issue by Takkster** [haubek/bootstrap4c-chosen#1]
Deprecated variables are used, e.g.:
error scss/style.scss (Line 9 of scss/chosen/_component-variables.scss: Undefined variable: "$input-box-shadow-focus".)
I think **$input-box-shadow-focus** is called **$input-focus-box-shadow** now

$gray-light => $gray-500
$brand-danger => theme-color("danger") (I think ...)

**Comment by haubek** [comment]
Thanks @Takkster -- I'll look into this.

**Comment by haubek** [comment]
This has now been fixed in latest release.
