### ISSUE TITLE
is-invalid in select element class not making borders red

### ISSUE THREAD

**Issue by dvilo** [haubek/bootstrap4c-chosen#12]
Hi, this works great overall (and now with border blur ;D)

I'm having an issue with server provided is-invalid which does not seem to be implemented yet.

The is-invalid is put in the select element  `id="test"` but chosen_single css expects it to be in a chosen-created element `id="test_chosen"`. 

I've hacked something that sort of works:
```
    $(".chosen-select").each(function() {
        var origId = "#" + this.id;
        var chosenId = "#" + this.id + "_chosen";
        if ($(origId).hasClass( "is-invalid" )) {
            $(chosenId).addClass( "is-invalid" );
        } else {
            $(chosenId).removeClass( "is-invalid" );
        }   
    });
```
This unfortunately makes the entire surround red (select box and dropdown).

Any tips or ideas of making it work without class manipulation?

Thanks!

**Comment by haubek** [comment]
Hi @dvilo -- The class `is-invalid` should only be added to the `<div class="chosen-container">` container... and removed or changed to `is-valid` when validated. Do you see a red border on the `.chosen-drop` container (see attachment)?
<img width="550" alt="12" src="https://user-images.githubusercontent.com/326914/56258642-9abf1e00-6113-11e9-8335-b33eba773bf9.png">

**Comment by haubek** [comment]
Check https://haubek.github.io/chosen/ "is valid" for example.

**Comment by dvilo** [comment]
Thanks @haubek.

I'm getting the same result using the jQuery posted above.

This is the same as you are doing in:
```
// Init validation
--
  | $('#is_valid_chosen').addClass('is-valid');
  | $('#is_invalid_chosen').addClass('is-invalid');
```
![chosen](https://user-images.githubusercontent.com/22210771/56269129-a4d52280-60fb-11e9-91ce-e452172533ba.PNG)

Since my page and validation is server-generated I have to add "is-invalid" somewhere. It seems to do no harm in the select container. 

If this is the required method, I'll be happy to use it. I thought that chosen would magically transfer classes in Select to `<div class="chosen-container">`. The issue is with chosen and not your css.
