### ISSUE TITLE
Required Select does not work

### ISSUE THREAD

**Issue by Arnoost** [haubek/bootstrap4c-chosen#3]
When I use jQuery Validation plugin or "required" for Browser validation, Chosen select is ignored.  
I have tried use "form-control-selected-required" but "select" does not change to Chosen style. Looks like standard BS4 select.

My code:
<select name="delivery" id="delivery" class="form-control form-control-chosen" required>
Works well but select is not controlled as "required"

Example  does not work too
<select id="required" class="form-control form-control-chosen-required" data-placeholder="Please select..." required>

**Comment by haubek** [comment]
Hi @Arnoost -- Thanks for creating this ticket. Are you able to post your code changes and I'll have a look at the issue?

**Comment by Arnoost** [comment]
Here is the part of the code and the screen image.

Online non-public code in in the url:
https://co.webdilna.com/shop/en/product-mumero-uno
But, you must Add product to cart. And go to Cart on right top corner and click to button - Go to the order. There is a code to view online. 
When do not fill in the form and click again to - Go to the order. You see validation as on the picture.

Really thanks 👍  :) 

![snimek obrazovky 2018-03-26 v 13 27 41](https://user-images.githubusercontent.com/33807014/37903898-fd84fe60-30f9-11e8-8524-b26221240080.png)
![snimek obrazovky 2018-03-26 v 13 24 38](https://user-images.githubusercontent.com/33807014/37903899-fda1699c-30f9-11e8-8161-2b30436bd85b.png)

**Comment by haubek** [comment]
Hi @Arnoost -- I've added support for `.is-valid` and `.is-invalid` to latest release v1.0.7 but you still have to add some JS that find the nearest class `chosen-container` and addClass `is-invalid`. Let me know if you still have issues with the component.

**Comment by Theolodewijk** [comment]
@haubek do you have some example ?

requered not working now https://gyazo.com/f34b8ca21cbb4e10e241fbb2bacbc488

```<div class="form-group row">
                            <label for="places" class="col-sm-3 col-form-label" title="">Plaats</label>
                            <div class="col">
                                <div class="input-group">
                                    <select id="places" class="form-control form-control-chosen" name="places" required>
                                        <option class="empty_places_option" value="" selected disabled>Selecteer de plaats</option>
                                        <?php $places = "SELECT * FROM places WHERE status = 1 ORDER BY places_id ASC"; $places = $db->query($places); foreach($places as $row) { ?>
                                        <option class="places_options" value="<?=$row['places_id']?>"><?=utf8_encode($row['name'])?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>```
