### ISSUE TITLE
Focus input is visible

### ISSUE THREAD

**Issue by aetna-softwares** [haubek/bootstrap4c-chosen#5]
The focus input is visible : 
![image](https://user-images.githubusercontent.com/8860618/40891253-81ba690e-6782-11e8-847d-c6b12bbf8b25.png)

I need to reintegrate the following rule from chosen original css : 
![image](https://user-images.githubusercontent.com/8860618/40891287-3452a2a2-6783-11e8-890b-e1926f1f2a14.png)

to make it work as expected

**Comment by haubek** [comment]
Thanks for picking this up. I released a new version that should fix the issue.

**Comment by aetna-softwares** [comment]
thanks !
