### ISSUE TITLE
Wrong position with prepend

### ISSUE THREAD

**Issue by strigefleur** [haubek/bootstrap4c-chosen#6]
Bootstrap 4.1.1, Chosen 1.8.6

Container gets moved to a new line if used in pair with Bootstrap prepend ([example](https://plnkr.co/edit/XL8LGsqofF5IIko40upM?p=preview)) instead of flexing inline.

**Comment by haubek** [comment]
Hi @strigefleur -- Fixed with the latest release (1.0.10).

**Comment by strigefleur** [comment]
Hello. That's nice! 
But yet it does not fit the original style: prepend and container have different height.
Testable with same plunkr.

**Comment by haubek** [comment]
Hello. Should work now. Your Plunkr is broken.
https://cdn.jsdelivr.net/npm/bootstrap4c-chosen@1.0.10/dist/css/bootstrap4c-chosen.min.css
isn't working. Maybe checkout the project and try `example.html`??

**Comment by strigefleur** [comment]
Aha. My bad, it's just about styles' load order. Good job.
