### ISSUE TITLE
Extra height

### ISSUE THREAD

**Issue by strigefleur** [haubek/bootstrap4c-chosen#9]
Chosen-select has more height than regular Bootstrap component.
Putting chosen-select next to another element within the same row makes it noticeable:

> <div class="form-row">
    <div class="form-group col-lg-9">
        <select id="chosen" multiple class="form-control form-control-chosen">
            <option>Option One</option>
            <option>Option Two</option>
        </select>
    </div>
    <div class="form-group col-lg-3">
        <div class="input-group">
            <input type="text" class="form-control" autocomplete="foo">
        </div>
    </div>
</div>

**Comment by haubek** [comment]
Hi @strigefleur -- It looks like you are right. It's 40px hight (should be 38px). I'll fix this and make a new release soon.

**Comment by haubek** [comment]
Hi @strigefleur -- That's now been fixed and released.
